language: node_js
node_js:
  - "node"
  - "lts/dubnium"
  - "lts/Erbium"
before_install:
  - "echo {} > $HOME/.pushfile.json"
notifications:
  email:
    recipients:
      - josh@jfin.us
  irc:
    channels:
      - "chat.freenode.net#bluefin.io"
    use_notice: true
