language: node_js
node_js:
  - "0.10"
  - "4.0"
  - "4.1"
  - "4.2"
notifications:
  email:
    recipients:
      - josh@jfin.us
  irc:
    channels:
      - "chat.freenode.net#bluefin.io"
    use_notice: true
